name: Sarkar94

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  Lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Super-Linte
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Netlify
    runs-on: ulatest
    needs: Lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publishDir: ./
          netlifySiteId: ${{ secrets.NETLIFY_SITE_ID }}
          netlifyToken: ${{ secrets.NETLIFY_AUTH_TOKEN }}
